apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
      - name: api
        image: tharunk132/fastapi-poc:1.0
        ports:
        - containerPort: 8000