apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
      - name: poc
        image: nginx:1.25
        ports:
        - containerPort: 80

